### ISSUE TITLE
Validated on 1 January 1970

### ISSUE THREAD

**Issue by ThomasTel** [France-ioi/AlgoreaPlatform#2]
It seems that there is an error of timestamp.
![bug-algorea-2](https://cloud.githubusercontent.com/assets/12912823/9464990/eaf0acd6-4b28-11e5-97c0-26afbb16627f.png)

**Comment by eroux** [comment]
fixed by https://github.com/France-ioi/AlgoreaPlatform/commit/dbf6aecc822ddc78d9e3de6c18e056ea1c692891
